#!/bin/sh

echo -n "enter the version : "
read version 
 
git add -A && git commit -m "Release ${version}"
git tag ${version}
git push --tags
git push origin master
pod trunk push --verbose --allow-warnings
