#!/bin/sh

echo -n "enter the version : "
read version 

echo "**************begin commit*********************"
git add -A && git commit -m "Release ${version}"

echo "***************begin tag***********************"
git tag ${version}

echo "**************begin push -tags*****************"
git push --tags

echo "**************begin push origin****************"
git push origin master

echo "**************begin trunk push*****************"
pod trunk push --verbose --allow-warnings
